server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
  application:
    name: detleprovid
  cloud:
    zookeeper:
      connect-string: localhost:2181
mapper:
  identity: MYSQL   #配置主键自动增长
logging:
  level:
    com.pzg.springcloud.app.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://admin:a@eureka1:7001/eureka,http://admin:a@eureka2:7002/eureka,http://admin:a@eureka3:7003/eureka
  instance:
    instance-id: provied-prodoct_1
info:
  app.name: DETLEPROVID
  company.name: pzg
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$

