server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: a
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    application:
      name: provied
  cloud:
    zookeeper:
      connect-string: localhost:2181
mapper:
  identity: MYSQL   #配置主键自动增长
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.pzg.springcloud.app.dao: debug